### ISSUE TITLE
Quilt native Groovy

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#18]
# Call Quilt from Groovy: bypass quilt3 command-line tool
Right now the plugin uses the command-line tool from the quilt3 pip package, specifically the 'install' and 'push' actions.
This is both an added dependency, and a 'blunt instrument'.  For example, the only way to get a list of all the files in a package is to first install the package then `ls` the install directory.

Alternatives include:

- Using "[JavaEmbeddedPython](http://ninia.github.io/jep/)" to call the Python API directly (which we tried initially, but failed due to threading issues)
- Building a Java (Groovy) client for reading and writing Quilt manifests

**Comment by drernie** [comment]
1. @dimaryaz  will create a quiltcore-java
2. nf-quilt will call that instead of quilt3
3. Install
4. Push
5. List

**Comment by drernie** [comment]
Proposed Integration Plan

https://github.com/quiltdata/nf-quilt/blob/main/plugins/nf-quilt/src/main/nextflow/quilt/jep/QuiltPackage.groovy

End Result:

1. First MIRROR the quilt3 calls with stub native calls
2. Implement GET/INSTALL replacement
3. Implementing PUT/PUSH replacement (*PATCH)
4. Optional: Replace install+directory_walk with actual LIST operations

**Comment by drernie** [comment]
Implementation Proposal

1. Ernie implements quiltcore.py using cross-platform abstractions
2. Rigorously document that via a YAML file
3. Dima leverages those to implement quiltcore.java

**Comment by drernie** [comment]
Things you can steal from nf-quilt:
- build.gradle (sort of)
- .github actions
- groovy config

**Comment by drernie** [comment]
Requires
        "url": "https://github.com/nextflow-io/nf-amazon/releases/download/1.16.2/nf-amazon-1.16.2.zip",

Download (via Makefile?) from https://github.com/nextflow-io/nf-amazon/releases

**Comment by drernie** [comment]
https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/main/nextflow/plugin/PluginsFacade.groovy

https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/test/nextflow/plugin/PluginsFacadeTest.groovy

**Comment by drernie** [comment]
The problem is that TestPluginManager seems to only load a SINGLE plugin.

Can I add a different plugin manager to load the regular plugins? Seemingly not.

> java.lang.UnsupportedOperationException: Install is not supported on dev mode - Missing plugin nf-amazon 1.16.2

**Comment by drernie** [comment]
Almost:
```log
22:19:43.595 [Test worker] DEBUG nextflow.plugin.PluginUpdater – Starting plugin nf-amazon version: 1.16.2
22:19:43.595 [Test worker] INFO  org.pf4j.AbstractPluginManager – Start plugin 'nf-amazon@1.16.2'
22:19:43.595 [Test worker] DEBUG org.pf4j.DefaultPluginFactory – Create instance for plugin 'nextflow.cloud.aws.AmazonPlugin'
22:19:43.599 [Test worker] ERROR org.pf4j.DefaultPluginFactory – nextflow.cloud.aws.AmazonPlugin
java.lang.ClassNotFoundException: nextflow.cloud.aws.AmazonPlugin
```
java.lang.NullPointerException: Cannot invoke "org.pf4j.Plugin.start()" because the return value of "org.pf4j.PluginWrapper.getPlugin()" is null
	at org.pf4j.AbstractPluginManager.startPlugin(AbstractPluginManager.java:392)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:154)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:328)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:333)
	at nextflow.plugin.PluginsFacade.load(PluginsFacade.groovy:232)
	at nextflow.plugin.PluginsFacade.setup(PluginsFacade.groovy:226)
	at nextflow.quilt.quiltcore.S3Test.should create paths for s3(S3Test.groovy:42)

**Comment by drernie** [comment]
Different error if 'prod' versus 'dev'. Oddly:
```log
22:27:45.027 [Test worker] DEBUG nextflow.plugin.PluginUpdater – Installing plugin nf-amazon version: 1.16.2
22:27:45.030 [Test worker] WARN  nextflow.file.FileHelper – Unable to start plugin 'nf-amazon' required by s3://quilt-example/.quilt
java.lang.UnsupportedOperationException: Install is not supported on dev mode - Missing plugin nf-amazon 1.16.2
```
java.lang.IllegalStateException: Missing plugin 'nf-amazon' required to read file: s3://quilt-example/.quilt
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:319)
	at nextflow.file.FileHelper.asPath(FileHelper.groovy:273)
	at nextflow.quilt.quiltcore.S3Test.should create paths for s3(S3Test.groovy:43)

**Comment by drernie** [comment]
Same problem as before:

```log
18:18:09.310 [Test worker] INFO  org.pf4j.AbstractPluginManager – Start plugin 'nf-amazon@1.16.2'
18:18:09.310 [Test worker] DEBUG org.pf4j.DefaultPluginFactory – Create instance for plugin 'nextflow.cloud.aws.AmazonPlugin'
18:18:09.384 [Test worker] ERROR org.pf4j.DefaultPluginFactory – nextflow.cloud.aws.AmazonPlugin
java.lang.ClassNotFoundException: nextflow.cloud.aws.AmazonPlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144)
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81)
	at org.pf4j.AbstractPluginManager.startPlugin(AbstractPluginManager.java:392)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:154)
```

**Comment by drernie** [comment]
https://www.javadoc.io/doc/org.pf4j/pf4j/3.4.1/org/pf4j/package-summary.html
https://github.com/pf4j/pf4j/tree/master/pf4j/src/main/java/org/pf4j

**Comment by drernie** [comment]
api 'org.pf4j:pf4j:3.4.1'
    api 'org.pf4j:pf4j-update:2.3.0'

https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
```java
        log.info("Start plugin '{}'", getPluginLabel(pluginDescriptor));
        pluginWrapper.getPlugin().start();
```
https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginWrapper.java
```java
            plugin = pluginFactory.create(this);
   // Plugin create(PluginWrapper pluginWrapper);
```
https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java
```java
            for (ClassLoadingStrategy.Source classLoadingSource : classLoadingStrategy.getSources()) {
                Class<?> c = null;
                try {
                    switch (classLoadingSource) {
                        case APPLICATION:
                            c = super.loadClass(className);
                            break;
                        case PLUGIN:
                            c = findClass(className);
                            break;
                        case DEPENDENCIES:
                            c = loadClassFromDependencies(className);
                            break;
                    }
                } catch (ClassNotFoundException ignored) {}

                if (c != null) {
                    log.trace("Found class '{}' in {} classpath", className, classLoadingSource);
                    return c;
                } else {
                    log.trace("Couldn't find class '{}' in {} classpath", className, classLoadingSource);
                }
            }

            throw new ClassNotFoundException(className);
```
    private ClassLoadingStrategy classLoadingStrategy;
https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ClassLoadingStrategy.java
https://www.includehelp.com/java/classloader-findclass-method-with-example.aspx

**Comment by drernie** [comment]
https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/PluginClassLoader.java
```java
/**
 * One instance of this class should be created by plugin manager for every available plug-in.
 * By default, this class loader is a Parent Last ClassLoader - it loads the classes from the plugin's jars
 * before delegating to the parent class loader.
 * Use {@link #classLoadingStrategy} to change the loading strategy.
 *
 * @author Decebal Suiu
 */
 public class PluginClassLoader extends URLClassLoader {
    public PluginClassLoader(PluginManager pluginManager, PluginDescriptor pluginDescriptor, ClassLoader parent, ClassLoadingStrategy classLoadingStrategy) {
        super(new URL[0], parent);

        this.pluginManager = pluginManager;
        this.pluginDescriptor = pluginDescriptor;
        this.classLoadingStrategy = classLoadingStrategy;
    }
import java.net.URLClassLoader
```

https://github.com/pf4j/pf4j/blob/860b79710de3b30f2fb9b67a05d5a1aa4926debd/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L227
```java
    public String loadPlugin(Path pluginPath) {
        if ((pluginPath == null) || Files.notExists(pluginPath)) {
            throw new IllegalArgumentException(String.format("Specified plugin %s does not exist!", pluginPath));
        }

        log.debug("Loading plugin from '{}'", pluginPath);

        PluginWrapper pluginWrapper = loadPluginFromPath(pluginPath);

        // try to resolve  the loaded plugin together with other possible plugins that depend on this plugin
        resolvePlugins();

        return pluginWrapper.getDescriptor().getPluginId();
    }
```

**Comment by drernie** [comment]
```java
                        case APPLICATION:
                            c = super.loadClass(className);
                            break;
                        case PLUGIN:
                            c = findClass(className);
                            break;
                        case DEPENDENCIES:
                            c = loadClassFromDependencies(className);
                            break;
```

**Comment by drernie** [comment]
Manually loading plugin finally failed on:
```groovy
class AmazonPlugin extends BasePlugin {

    AmazonPlugin(PluginWrapper wrapper) {
        super(wrapper)
    }

    @Override
    void start() {
        super.start()
        FileHelper.getOrInstallProvider(S3FileSystemProvider)
    }
}
```
with:
```log
java.lang.reflect.InaccessibleObjectException: Unable to make field private static volatile java.util.List java.nio.file.spi.FileSystemProvider.installedProviders accessible: module java.base does not "opens java.nio.file.spi" to unnamed module @29428716
	at nextflow.file.FileHelper.getOrInstallProvider(FileHelper.groovy:639)
```
The simplest solution might be to just catch the error and re-implement FileHelper.

**Comment by drernie** [comment]
Hmm. Others seem to have had this issue:
https://github.com/nextflow-io/nextflow/issues/1963
https://github.com/nextflow-io/nextflow/issues/1964

> Installation != plugin requirement/activation. Installation means only downloading, unzipping and copy the plugin content into the HOME/.nextflow/plugins folder.

But, their solution still seems to (obviously) require running nextflow. Hmm.

**Comment by drernie** [comment]
Completed via quiltcore-java.
