### ISSUE TITLE
debug-validation

### ISSUE THREAD

**Issue by drernie** [quiltdata/nf-quilt#207]
Running with an [S3 URI](https://cloud.seqera.io/orgs/Quilt_Data/workspaces/hackathon_2023/watch/jkmgJMO7cy7bB) or [nf-quilt@0.4.5](https://cloud.seqera.io/orgs/Quilt_Data/workspaces/hackathon_2023/watch/URi0pljDk0Evt) completes successfully.

Running with the latest nf-quilt plugin crashes during the input validation phase after this error:

> ERROR ~ No such file or directory: /tmp/QuiltPackage5049614505086286284/QuiltPackage.bfx_input_index_fetchngs_cellarity_nfcore_fetchngs_tpdi_292/pipeline_info/params_2024-06-11_20-17-30.json

Such a hard error it does not generate a log!  Implies we are not catching the error somewhere.

**Comment by drernie** [comment]
./launch.sh run 'https://github.com/nf-core/fetchngs' \
                 -name test_fetchngs \
                 -params-file ./fetchngs-params.json \
                 -with-tower \
                 -r 1.12.0 \
                 -profile docker \
                 -latest

 N E X T F L O W   ~  version 24.03.0-edge

Pulling nf-core/fetchngs ...
 downloaded from https://github.com/nf-core/fetchngs.git
Launching `https://github.com/nf-core/fetchngs` [test_fetchngs] DSL2 - revision: 8ec2d934f9 [1.12.0]

ERROR ~ Cannot invoke "org.pf4j.Plugin.start()" because the return value of "org.pf4j.PluginWrapper.getPlugin()" is null

**Comment by drernie** [comment]
Huh
```
installing nf-quilt/sarek from quilt-example...
ERROR ~ failed to install nf-quilt/sarek

 -- Check '.nextflow.log' file for details
ERROR ~ Install is not supported on dev mode - Missing plugin nf-validation 
```

**Comment by drernie** [comment]
Okay, I find this error with sarek also:
```
../nextflow/nextflow run nf-core/sarek -profile test,docker -plugins nf-quilt@0.7.12 --outdir "quilt+s3://quilt-example#package=nf-quilt/sarek"


 N E X T F L O W   ~  version 24.04.0-edge

Launching `https://github.com/nf-core/sarek` [crazy_newton] DSL2 - revision: b5b766d3b4 [master]

installing nf-quilt/sarek from quilt-example...
ERROR ~ failed to install nf-quilt/sarek

 -- Check '.nextflow.log' file for details
ERROR ~ No such file or directory: /var/folders/tz/8q322ht10qzf9pswh01zv6880000gp/T/QuiltPackage1814548995306102923/QuiltPackage.quilt_example_nf_quilt_sarek/pipeline_info/params_2024-06-13_12-12-27.json

 -- Check script '/Users/ernest/.nextflow/assets/nf-core/sarek/./workflows/sarek/../../subworkflows/local/utils_nfcore_sarek_pipeline/../../nf-core/utils_nextflow_pipeline/main.nf' at line: 85 or see '.nextflow.log' file for more details
```

**Comment by drernie** [comment]
[Ah! When I use nf-quilt latest instead of 0.7.11, I get the error.]
DUE TO TYPO

**Comment by drernie** [comment]
Hmm. Can't run nf-validation in dev mode, and get `WARN: Path integrity check failed` when I try to run production.

**Comment by drernie** [comment]
Doh. nf-quilt failed due to typo. Also, v12 wasn't in public repo.

 Checking again to see if v9 or v12 actually makes the default nf-quilt job fail. Also trying fetchngs with v12.

**Comment by drernie** [comment]
Sigh. v0.7.12 has the same problem. AND testing nf-quilt default (0.7.9) doesn't give me a valid error :-(

```
Downloading plugin nf-quilt@0.7.12
installing nf-core/fetchngs from nf-core-gallery...
Children: [ccle_ids.csv]
Downloading plugin nf-validation@1.1.3
ERROR ~ No such file or directory: /tmp/QuiltPackage9630287772571825406/QuiltPackage.nf_core_gallery_nf_core_fetchngs/pipeline_info/params_2024-06-13_23-27-47.json
 -- Check script '.nextflow/assets/nf-core/fetchngs/./subworkflows/local/utils_nfcore_fetchngs_pipeline/../../nf-core/utils_nextflow_pipeline/main.nf' at line: 85 or see 'nf-3UrUPdcJgiOeqi.log' file for more details
```

**Comment by drernie** [comment]
Okay, can reproduce locally with `make sarek NF_BIN=../nextflow/nextflow`
[nextflow.log](https://github.com/user-attachments/files/15829756/nextflow.log)

**Comment by drernie** [comment]
```
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at nextflow.quilt.nio.QuiltPath.deinstall(QuiltPath.groovy:85)
	at nextflow.quilt.nio.QuiltFileSystemProvider.upload(QuiltFileSystemProvider.groovy:151)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:959)
```
