### ISSUE TITLE
Problem Updating Existing package

### ISSUE THREAD

**Issue by wosmanitx** [quiltdata/nf-quilt#86]
Hi,

I attempted to update an existing package and received the following error:
```

java.lang.NullPointerException: Cannot invoke "nextflow.quilt.nio.QuiltPath.pkg()" because "path" is null
	at nextflow.quilt.QuiltProduct.<init>(QuiltProduct.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.doCall(QuiltObserver.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.call(QuiltObserver.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2395)
	at nextflow.quilt.QuiltObserver.onFlowComplete(QuiltObserver.groovy:92)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1074)
	at nextflow.Session.shutdown0(Session.groovy:702)
	at nextflow.Session.destroy(Session.groovy:644)
	at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:239)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:134)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
```
	
Command invocatoin:

```
Command

quarto render enceladus.qmd \
-P benchling_ID:EXP23000277 \
-P core_file_type:saint_output \
-P msigdb_pathways_reactome_file:c2.cp.reactome.v7.5.symbols.gmt \
-P msigdb_hpo_file:c5.hpo.v7.5.symbols.gmt \
-P msigdb_hallmark_file:h.all.v7.5.symbols.gmt \
-P msigdb_immunesigdb_file:c7.immunesigdb.v7.5.symbols.gmt \
-P uniprot_map_file:uniprot-map.tsv \
-P msstats_comparison_results_file:msstats_comparison_results_180_EXP23000277_SLC15A4-PR_APMS_TMTpro_F-SLC15A4_RTS_Fractions_BaitNormalized.csv \
-P msstats_protSum_file:msstats_protein_summary_180_EXP23000277_SLC15A4-PR_APMS_TMTpro_F-SLC15A4_RTS_Fractions_BaitNormalized.csv \
-P apms_saint_results_file:EXP23000277_SLC15A4-PR_APMS_LFQ_F-SLC15A4_R848_PSM_saint-output-92-141.dat
```

Please help! 

Thanks

**Comment by drernie** [comment]
It looks like the URI that triggered the error is:
```
Apr-25 15:17:11.971 [PublishDir-2] DEBUG nextflow.quilt.QuiltObserver - onFilePublish.QuiltPath[interline-proteomics-analysis#package=SLC15A4%2fEXP23000277&path=enceladus_output]: paths=[null]
```
And that package `SLC15A4%2fEXP23000277` already existed before you began this run, correct?

**Comment by wosmanitx** [comment]
yes, it did. Runs fine with new packages.

**Comment by wosmanitx** [comment]
I believe the error was on our end.

**Comment by wosmanitx** [comment]
Hi I am actually seeing this error again. We are attempting to update a package which has not originally created by the nf-quilt plugin. Packages that were previously created via nf-quilt can be updated via nf-quilt, but existing packages that were not created initially by nf-quilt are producing this error:

```
May-03 13:58:01.542 [main] DEBUG io.seqera.tower.plugin.TowerReports - Saved reports file s3://interline-tower-bucket/scratch/3Yq2tuKdDKTzmY/nf-3Yq2tuKdDKTzmY-reports.tsv
May-03 13:58:02.298 [main] DEBUG nextflow.quilt.QuiltObserver - `onFlowComplete` [null]
May-03 13:58:02.308 [main] DEBUG nextflow.Session - Failed to invoke observer completion handler: nextflow.quilt.QuiltObserver@6be2b567
java.lang.NullPointerException: Cannot invoke "nextflow.quilt.nio.QuiltPath.pkg()" because "path" is null
	at nextflow.quilt.QuiltProduct.<init>(QuiltProduct.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.doCall(QuiltObserver.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.call(QuiltObserver.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2395)
	at nextflow.quilt.QuiltObserver.onFlowComplete(QuiltObserver.groovy:92)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1074)
	at nextflow.Session.shutdown0(Session.groovy:702)
	at nextflow.Session.destroy(Session.groovy:644)
	at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:239)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:134)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
	```

**Comment by drernie** [comment]
1. Confirmed I can update the usual 'test/hurdat' package w/23.04.0
2. Confirmed I can create a new 'test/waleed' package
3. Confirmed I can update that package
4. Testing whether I can update a completed different package...
```
make pkg-test TEST_URI="quilt+s3://quilt-ernest-staging#package=test/observer-306173261"
```
SUCCESS: QuiltPackage.quilt_ernest_staging_test_observer_306173261

**Comment by drernie** [comment]
Custom patch https://github.com/quiltdata/nf-quilt/releases/tag/0.3.6-debug

**Comment by drernie** [comment]
This appears to due to the backward incompatible changes in 23.1 which were resolved before the first public release.

But are still in your Enterprise build 23.1.0-cycle07_4487eca

**Comment by drernie** [comment]
I believe we resolved this. If not, please re-open.
