### ISSUE TITLE
Unable to pull packages

### ISSUE THREAD

**Issue by wosmanitx** [quiltdata/nf-quilt#87]
Not sure whats going on here, I think it may be related to a recent update?

```
May-03 13:58:02.308 [main] DEBUG nextflow.Session - Failed to invoke observer completion handler: nextflow.quilt.QuiltObserver@6be2b567
java.lang.NullPointerException: Cannot invoke "nextflow.quilt.nio.QuiltPath.pkg()" because "path" is null
	at nextflow.quilt.QuiltProduct.<init>(QuiltProduct.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.doCall(QuiltObserver.groovy:92)
	at nextflow.quilt.QuiltObserver$_onFlowComplete_closure2.call(QuiltObserver.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2395)
	at nextflow.quilt.QuiltObserver.onFlowComplete(QuiltObserver.groovy:92)
	at nextflow.Session.notifyFlowComplete(Session.groovy:1074)
	at nextflow.Session.shutdown0(Session.groovy:702)
	at nextflow.Session.destroy(Session.groovy:644)
	at nextflow.script.ScriptRunner.shutdown(ScriptRunner.groovy:239)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:134)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
May-03 13:58:02.318 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
```

**Comment by drernie** [comment]
As we discussed, the issue is that:

1. publishDir only uses the "local" path, and I have to infer the original URI
2. pattern matching on the 'params' results in my finding `quilt+s3://interline-proteomics-analysis#package=SLC15A4/EXP23000415@28c802bc0cd43f61d5f02a43b3cadea2c33049ad5c3220d890ef42ef8c8b3da7&path=msstats%2Fprotein%2Fprotein_summary.csv` which doesn't contain metadata
3. If you add metadata to that, it then fails because I don't know how to write to a URI containing a non-trivial "path"

Eventually we would like to intelligently support writing to subfolders, but for now I should just strip out the path so we write directly to the package.
